workflows:
  android-workflow:
    name: 247votes
    environment:
      vars:
        KEYSTORE: Encrypted(Z0FBQUFBQmdwVDBuaXJyMWR0eEozcFhVM0VyTmdIdDBnV1FWZ09sTXRoZmtsOHRkaFNjOFR1VkM3NjNkeHItWktfS2RJVmUzNUdOUVFtMzA3S21MN3NfLTJjZzhQV2V1U0JxdGp3RDF0eXlhdFZSSXRQZF9uS3c9) # <-- Put your encrypted keystore file here
        KEYSTORE_PATH: '/tmp/247votes.keystore'
        KEYSTORE_PASSWORD: Encrypted(Z0FBQUFBQmdwUjI5NXFvSmVDalVBMkVhX0hkdHA5NTNBa2M3ZkFOeWwxQTBTeUFRUGJvUUhSTmx3Nks1R3NyNTA4bHhOU0liWTlTRnhUSlI0RW44MGM0N1lBeFlPMlVqUHc9PQ==) # <-- Put your encrypted keystore password here
        KEY_ALIAS_PASSWORD: Encrypted(Z0FBQUFBQmdwUjI5NXFvSmVDalVBMkVhX0hkdHA5NTNBa2M3ZkFOeWwxQTBTeUFRUGJvUUhSTmx3Nks1R3NyNTA4bHhOU0liWTlTRnhUSlI0RW44MGM0N1lBeFlPMlVqUHc9PQ==) # <-- Put your encrypted keystore alias password here
        KEY_ALIAS: Encrypted(Z0FBQUFBQmdwVDFkSkJQMFBGR3BReHZnVFFyWjFJZFcyemxPd0NKWUN3aFM4RXduR0VHcm5tQ1VSXzR6cTUtTHpkWHdJRDE2b1lMRVFDdlFJSmwtN3N5ckZRTTdvX3p1V0E9PQ==) # <-- Put your encrypted alias password here
      xcode: 12.4
      node: 12
      npm: 6
    cache:
      cache_paths:
        - $FCI_BUILD_DIR/node_modules
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm ci
          cvm install 9.0.0
          cvm use 9.0.0                  
      - name: Add Android platform
        script: |
          set -x
          cordova platform remove android --nosave
          cordova platform add android --confirm --no-interactive --noresources          
      - name: Build Android
        script: |
          set -x
          set -e
          cordova build android --release --no-interactive --prod --device
          echo $KEYSTORE | base64 --decode > $KEYSTORE_PATH
          UNSIGNED_APK_PATH=$(find platforms/android/app/build/outputs -name "*.apk" | head -1)
          jarsigner -sigalg SHA1withRSA -digestalg SHA1 -keystore "${KEYSTORE_PATH}" -storepass "${KEYSTORE_PASSWORD}" -keypass "${KEY_ALIAS_PASSWORD}" "${UNSIGNED_APK_PATH}" "${KEY_ALIAS}"
          mv $UNSIGNED_APK_PATH $(echo $UNSIGNED_APK_PATH | sed 's/-unsigned//')          
    artifacts:
      - platforms/android/app/build/outputs/**/*.apk
      - platforms/android/app/build/outputs/**/mapping.txt
    publishing:
      # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email
      email:
        recipients:
          - support@callysconcept.com
          - callysconcept@gmail.com
        notify:
          success: true     # To receive a notification when a build succeeds
          failure: false    # To not receive a notification when a build fails
      slack:
        # See the following link about how to connect your Slack account - https://docs.codemagic.io/publishing-yaml/distribution/#slack
        channel: '#channel-name'
        notify_on_build_start: true   # To receive a notification when a build starts
        notify:
          success: true               # To receive a notification when a build succeeds
          failure: false              # To not receive a notification when a build fails
     
